### ISSUE TITLE
Documento de validación

### ISSUE THREAD

**Issue by abelorian** [TransbankDevelopers/feedback-general#10]
El documento de validación está en docx y no abre bien en otros editores como Pages. Dice que faltan fuentes y además los checkbox no son chequeables.

![image](https://user-images.githubusercontent.com/544935/76989057-863b6500-6924-11ea-847b-3792bd81378e.png)

Tampoco funciona bien al importarlo en Google Docs:

![image](https://user-images.githubusercontent.com/544935/76994102-aec75d00-692c-11ea-8a16-35b131c0b747.png)

https://transbankdevelopers.cl/files/evidencia-integracion-webpay.docx

**Comment by alectrico-pro** [comment]
Hola, me pasa lo mismo. Creo que Transbank hará ese proceso en forma automatizada. Por el momento automatizaré la confección del documento en formato pdf. Ya me ha pasado que cometo errores al transcribir los números.
