### ISSUE TITLE
***Error en Query SQL*** plugin Prestashop

### ISSUE THREAD

**Issue by msaustral** [TransbankDevelopers/feedback-general#11]
Hola hay un error en el query que se encuentra en PS_Instillation/modules/webpay/controllers/front/validate.php en línea 51. 

Si al instalar el Prestashop se le coloco un prefijo diferente a PS_ a las tablas, el modulo da error por no conseguirla.

La línea se debe cambiar para que se ajuste a las mejores practicas de Prestashop al siguiente código:

`$sql = "SELECT id_cart FROM "._DB_PREFIX_."cart p WHERE p.id_customer = $id_usuario ORDER BY p.id_cart DESC";`

Con este cambio se resuelve el error, saludos.

**Comment by gdespirito** [comment]
Hola! Creo que eso está resuelto en el plugin REST :)
Disculap al demora en contestar.
