### ISSUE TITLE
Error de incompatibilidad de módulo de Prestashop con otros módulos

### ISSUE THREAD

**Issue by msaustral** [TransbankDevelopers/feedback-general#12]
Hola al usar el módulo de webpay con otros módulos, por ejemplo, one page checkout, este no funciona ya que en el constructor de hookPaymentOptions en el archivo webpay.php no se le pasa el campo mudule name.

Para corregirlo abrimos el archivo PS_installation/modules/webpay/webpay.php en la línea 147 agregamos:
`$WPOption->setModuleName($this->name);`

Falla resuelta!, saludos.

**Comment by gdespirito** [comment]
Hola @msaustral. ¿Este problema sigue existiendo hoy en día en el plugin REST?

Gracias por tu comentario y disculpa la demora en contestar.

**Comment by msaustral** [comment]
Hola @gonzunigad aun no pruebo la nueva ver del módulo, valido con una nueva implementación que tenemos y te comento, saludos, feliz año
