### ISSUE TITLE
SDK PHP Retorna respuesta vacia

### ISSUE THREAD

**Issue by zorrokurama** [TransbankDevelopers/feedback-general#13]
Buenas tardes, tengo un serio problema con el SDK de webpay. Sucede que lleva semanas el problema de que a un cliente de mi plataforma, le cobran el dinero pero en retorno de los datos webpay no me retorna nada. Y lo sé porque tengo un archivo de Log que escribe el detalle de lo que este me retorna. Quisiera saber por favor como debo proceder? para que esto no suceda?

**Comment by alectrico-pro** [comment]
Hola, este es mi primer aporte. Según entiendo Ud. tiene una queja sobre una herramienta existente. Entiendo que eso debe hacerlo en slack.com.

**Comment by gdespirito** [comment]
Hola @zorrokurama ! Escríbenos en el Slack de la comunidad (https://join-transbankdevelopers-slack.herokuapp.com/) para comentarnos más detalles
