### ISSUE TITLE
Agregar parámetro Custom en WebPayPlus REST

### ISSUE THREAD

**Issue by alectrico-pro** [TransbankDevelopers/feedback-general#14]
### Agregar parámetro Custom en WebPayPlus REST

Hola, ya integré WebpayPlus REST. Funciona bien y de acuerdo a lo que esperaba.

Me gustaría disponer libremente de un params de request html en la api rest de WP, que pueda enviar a Transbank durante la creación de la transacción y que pueda recibir de vuelta sin modificación alguna. 

Esa es mi sugerencia.

Lo puedo usar para acortar el tiempo de ida a Transbank, que es algo crítico para la mayor de los usuarios. Si la experiencia de compra es buena al inicio, puedo más tarde disponer del tiempo ahorrado.

Existen los campos sessionId, buy_order y return_url que son excelente idea pero aún así me conviene tener un params extenso o unos tres o cuatro cortos. También valoraría si el campo fuese lo suficientemente extenso para contener algún token jwt.

**Comment by gdespirito** [comment]
Hola @alectrico-pro! Gracias por tu sigerencia.  ¿que evita que puedas usar el token que genera transbank en la respuesta, que es único e irrepetible, para guardar en tu sistema info asociada?

Digo, creas la transacción, se genera el token y en tu base de datos guardas toda la info que necesites, y cuando llegue la respuesta del usuario de vuelta con el token, buscas en tu base de datos los datos asociados a es token.

**Comment by alectrico-pro** [comment]
Hola,!Feliz 202!

La idea del campo custom no es mía, la usan en Khipu, pero la idea del token en un campo de ida y vuelta tal vez sea mía, me sería útil y me permitría blindar datos.

No pretendo desacreditar el token de pago de Transbank, es otra cosa.
