### ISSUE TITLE
Integración con GPay y Apple pay

### ISSUE THREAD

**Issue by blackshot** [TransbankDevelopers/feedback-general#27]
tal cual dice el título, necesitan empezar a diferenciarse entre tanta competencia de pasarela de pago y es algo que está entrando fuerte en chile. 

serían los pioneros, podrían hacerle hasta publicidad.

que cómodo sería entrar a la pasarela de pago, hacer click en gpay, seleccionar la tarjeta asociada a mi cuenta de gmail y listo. que cómoda la pasarela.

**Comment by blackshot** [comment]
completado?

**Comment by mastudillot** [comment]
Hola, perdona que no dejara comentario. Normalmente las personas no contestan después de tanto tiempo. Apple Pay fue agregado a los pagos presenciales POS. En los pagos no presenciales no cuento con información.

Cerré el mensaje debido a que no es una funcionalidad que podamos proveer desde las herramientas de integración de Transbank Developers.

Saludos.
