### ISSUE TITLE
WebPay Plus para Servicios sin carrito de compras

### ISSUE THREAD

**Issue by NicooBrown** [TransbankDevelopers/feedback-general#28]
Realizar el pago de un servicio sin carrito de compras con woocommerce, poder visualizar un select con los respectivos servicios y sus valores, hacer click en el servicio que el cliente desea y pagar desde ese mismo formulario y no tener que pasar por agregar al carrito, ir al checkout, rellenar la información y recién proceder al pago.

**Comment by mastudillot** [comment]
Hola, nuestro plugin solo tiene la funcionalidad del pago con Webpay y Oneclick, la lógica del carro es propia de Woocommerce, es posible que encuentre un Plugin que te permita no usar carrito y comprobar si es compatible con nuestro Plugin.
