### ISSUE TITLE
Consultar una transacción después de haber sido procesado (webpay plus)

### ISSUE THREAD

**Issue by jeansjave** [TransbankDevelopers/feedback-general#4]
Esto seria necesario para poder consultar toda transacción vía API, que haya sido procesado via webpay plus.
Me ha pasado que un cliente hizo el pago de un producto desde mi página web que transbank entregue como respuesta rechazado, pero a los 2 días fue aprobado la transacción, pero en mi sistema ya habia quedado como rechazado el pedido, por esta razón sería necesario poder consultrar las transacciones.

**Comment by DarkGhostHunter** [comment]
No sabía que podía pasar eso. ¿No hay algún panel en Webpay para mirar el resultado de las transacciones?

**Comment by cavoso** [comment]
solo el panel de transbank el cual muchas veces hay que buscar las transacciones por monto, lo cual igual es poco practico
