### ISSUE TITLE
SDK webpay para Go

### ISSUE THREAD

**Issue by maugant** [TransbankDevelopers/feedback-general#6]
Go es simple en su sintaxis, concurrente y con un propósito, hacer aplicaciones web. Hace tiempo que trabajo con el y veo constantemente como otros nuevos emprendimientos lo utilizan. Ya cuenta con 10 años de desarrollo y con una comunidad amplia de colaboradores. Véase el indice TIOBE que ubica Go en el puesto [#15](https://tiobe.com/tiobe-index/) (popularidad) por sobre Ruby.

**Comment by cagodoy** [comment]
@gonzunigad alguna novedad con esto? 👀

**Comment by cagodoy** [comment]
Al final hice una implementación para lo que necesitaba.

https://github.com/microapis/transbank-sdk-golang

**Comment by gdespirito** [comment]
Excelente!
