### ISSUE TITLE
Elegir credito o débito al iniciar la transacción

### ISSUE THREAD

**Issue by abelorian** [TransbankDevelopers/feedback-general#7]
Poder elegir si pago con crédito o con débito antes de iniciar la transacción. Esto es útil para poder saber el costo de tbk y hacer descuentos si paga con débito.

No sé si esta opción existe actualmente. La he visto en Falabella, pero no encuentro la documentación oficial de TBK.

**Comment by gdespirito** [comment]
Hola! gracias por tu comentarios. Comercialmente puedes solicitar que no exista uno u otro producto. 
Puedes tener dos (o más códigos de comercio) cada uno con una configuración (solo débito o solo crédito) y así poder gestionar ese caso de uso. 

De todas formas, creo que hoy el modelo de tarifas ya no depende directamente de si es débito o crédito, si no de más factores.
